### ISSUE TITLE
微信小程序商城 没有微信登录功能，注册账号需要填写图形验证码，但是弹出的键盘只能输入数字，根本无法注册成功账号

### ISSUE THREAD

**Issue by ericheroster** [gooking/uni-app--mini-mall#2]
![微信图片_20230809101052](https://github.com/gooking/uni-app--mini-mall/assets/250643/d0349d8e-9833-47f2-86ec-140f510ec494)

**Comment by gooking** [comment]
后台验证码设置，把验证码设置成纯数字，手机输入字母验证码体验不好
